### ISSUE TITLE
[Bug] vt.tiktok.com (localized tiktok links?) are not working

### ISSUE THREAD

**Issue by BloodDragooner2** [Britmoji/tiktxk#1]
The expected behavior was for it to give the link, but it didn't.

[The test link is here](https://vt.tiktok.com/ZSRcT41U3/)

**Comment by KodingDev** [comment]
Don't believe it's localized, I think it's just a part of the link since it's tailored to whoever shared it afaik. Will push a fix for adding this subdomain though, weird that it exists but TikTok will do TikTok things 😄 Thanks for the report

**Comment by BloodDragooner2** [comment]
You're welcome! I say localized, since I've seen `ko` for TikTok Korea, too. Cheers for the fix!!

**Comment by BloodDragooner2** [comment]
Update, found a list of Tiktok domains, here: 
![image](https://user-images.githubusercontent.com/117775945/201454134-c7d2f175-91ab-4505-93ab-8068c50965c3.png)
https://gist.github.com/adryd325/2d5d37ba2863cd6636e4a3f26a14b0d1 source for the image [is here on this Gist](https://gist.github.com/adryd325/2d5d37ba2863cd6636e4a3f26a14b0d1)

**Comment by KodingDev** [comment]
Really good to know, have added them, to the worker, thanks a lot :)
