### ISSUE TITLE
All links broken

### ISSUE THREAD

**Issue by wobkobi** [Britmoji/tiktxk#10]
<html><body>

If you're here, and have no idea what this nerd shit is, something went wrong when trying to embed a TikTok video. We don't support slideshows or LIVE videos, and we can't show videos that are private, or have been deleted. Sorry! Something wrong? Open an issue on GitHub at https://tiktxk.com/issue <3"
--
error | "Unexpected end of JSON input"
success | false

</body>
</html>

from here but any one of them is the same 
https://tiktxk.com/ZSFf73EXH/

**Comment by DJtheRedstoner** [comment]
Fixed and deployed. Thanks for the report.
