### ISSUE TITLE
Broken due to tiktok api changes

### ISSUE THREAD

**Issue by DJtheRedstoner** [Britmoji/tiktxk#11]
Related: yt-dlp/yt-dlp#9506

Switching to another API may be required.

**Comment by wobkobi** [comment]
"Unexpected end of JSON input"
error?

**Comment by Scrazeloppe** [comment]
Not embedding anymore please fix

**Comment by KodingDev** [comment]
Fixed: https://github.com/Britmoji/tiktxk/commit/458067f385064fe7a9ca0ef2ab90464429481b91
