### ISSUE TITLE
Support shortened tiktok links

### ISSUE THREAD

**Issue by seriaati** [Britmoji/tiktxk#13]
Example: https://www.tiktok.com/t/ZPRTWfpxV
Currently https://www.tiktxk.com/t/ZPRTWfpxV just shows an error.
![image](https://github.com/Britmoji/tiktxk/assets/61446626/83f8e9d0-84b2-4553-96c4-25c1cd522c23)

**Comment by robostrange** [comment]
Came here to report the same issue.

**Comment by smiba** [comment]
I think it's just broken for now, vm.tiktok.com videos also nearly always show this error. Probably something changed on the API level

EDIT: Fixed in #15, but this is a bandage fix that will only work for as long as bytedance doesn't ban the new app install id.

**Comment by DeJayDev** [comment]
Closed by #15, thanks again.
