### ISSUE TITLE
Add proper slideshow support

### ISSUE THREAD

**Issue by Apocolypto** [Britmoji/tiktxk#6]
When embedding slideshows using tiktxk, it shows a static image of the first slide of the slideshow.

Is it possible that you could implement it so that all the slides within a slideshow play in a video format?

**Comment by KodingDev** [comment]
Currently we host the service via Cloudflare Workers. We've got very strict processing limits on it, so rendering a stitched image alone is really stretching the limits of it (I've looked into it before).

If you know of any self-hosted services that could do that processing for us, then I'd be happy to host it myself and integrate it, however - at this moment - I haven't found a super nice way to integrate it how I'd like.

If Discord allowed us to supply multiple images for the embed and could display it natively like it does for Twitter, then that'd be the preferred solution.

Appreciate it however, thank you ! I'll keep it open in case something pops up later

**Comment by IkeVoodoo** [comment]
@KodingDev You could edit the embed to change the image and add an action button to swipe left/right

**Comment by KodingDev** [comment]
We don't have access to buttons using raw HTTP embeds.

**Comment by Apocolypto** [comment]
My bad, I forgot about this thread. You could take a similar approach to vxtiktok where it shows all the images in a slideshow in a playable video format.

**Comment by Apocolypto** [comment]
update to this: discord supports up to 4 images that are embeddable now

**Comment by KodingDev** [comment]
Fixed :] Discord doesn't like embedding them sometimes, can't really do much about it, but it does work :)
