### ISSUE TITLE
"Unexpected end of JSON input" when embedding

### ISSUE THREAD

**Issue by Permanently** [Britmoji/tiktxk#7]
When trying to input a video, it reports back an unexpected end of JSON. 

**Example link:** https://www.tiktxk.com/@bzyxjbl/video/7303572800042847520

**Response:** 
```
{
  "_comment": "If you're here, and have no idea what this nerd shit is, something went wrong when trying to embed a TikTok video. We don't support slideshows or LIVE videos, and we can't show videos that are private, or have been deleted. Sorry! Something wrong? Open an issue on GitHub at https://tiktxk.com/issue <3",
  "error": "Unexpected end of JSON input",
  "success": false
}
```

**Comment by smiba** [comment]
Experiencing the same issue with the following video https://vm.tiktxk.com/ZIJnHrUCe/

Video works fine without tiktxk, it's not private

**Comment by w4tchdoge** [comment]
Having the same issue when I try to use tiktxk on the following link: https://www.tiktok.com/t/ZTL2SmoGF/

Both the link and the accompanying video load fine when I visit the URL using ProxiTok ([link](https://proxitok.belloworld.it/@su1ryu/video/7347804587450993953))

**Comment by KodingDev** [comment]
Fixed https://github.com/Britmoji/tiktxk/commit/458067f385064fe7a9ca0ef2ab90464429481b91
